# Generated by Django 6.0.3 on 2026-03-04 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arva', '0002_project_is_private_userprofile_layout_preference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='ai_analyzed_at',
            field=models.DateTimeField(blank=True, help_text='Last AI analysis timestamp', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='ai_complexity',
            field=models.CharField(blank=True, help_text='AI-estimated complexity', max_length=10),
        ),
        migrations.AddField(
            model_name='task',
            name='ai_estimated_hours',
            field=models.IntegerField(blank=True, help_text='AI-estimated hours to complete', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='ai_priority_reason',
            field=models.TextField(blank=True, help_text='AI reasoning for priority recommendation'),
        ),
        migrations.AddField(
            model_name='task',
            name='ai_priority_score',
            field=models.IntegerField(blank=True, help_text='AI-calculated priority score (1-100)', null=True),
        ),
    ]
