# Generated by Django 4.2.25 on 2025-11-28 03:01

import arva.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arva', '0002_userprofile_avatar_icon_alter_userprofile_google_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Arviga Project Manager', max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=arva.models.logo_path)),
                ('favicon', models.ImageField(blank=True, null=True, upload_to=arva.models.favicon_path)),
                ('primary_color', models.CharField(default='#09affe', max_length=20)),
                ('footer_text', models.CharField(default='© 2025 Arva', max_length=200)),
                ('support_email', models.EmailField(default='info@arviga.co.id', max_length=254)),
                ('maintenance_mode', models.BooleanField(default=False)),
            ],
        ),
    ]
