# Generated by Django 4.2.25 on 2025-11-28 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arva', '0003_websitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitesettings',
            name='body_bg',
            field=models.CharField(default='#f7f7f7', max_length=20),
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='custom_css',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='navbar_bg',
            field=models.CharField(default='#ffffff', max_length=20),
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='text_color',
            field=models.CharField(default='#333333', max_length=20),
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='theme_mode',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('auto', 'Auto')], default='light', max_length=10),
        ),
        migrations.AlterField(
            model_name='websitesettings',
            name='footer_text',
            field=models.CharField(default='© 2025 Arviga Project Manager', max_length=200),
        ),
        migrations.AlterField(
            model_name='websitesettings',
            name='support_email',
            field=models.EmailField(default='support@arviga.co.id', max_length=254),
        ),
    ]
