# Generated by Django 4.2.25 on 2025-11-28 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arva', '0004_websitesettings_body_bg_websitesettings_custom_css_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='phone',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='theme_preference',
            field=models.CharField(choices=[('inherit', 'Ikuti Website'), ('light', 'Light'), ('dark', 'Dark'), ('auto', 'Auto')], default='inherit', max_length=10),
        ),
        migrations.AlterField(
            model_name='websitesettings',
            name='navbar_bg',
            field=models.CharField(default='#09affe', max_length=20),
        ),
    ]
