# Generated by Django 4.2.25 on 2025-11-28 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arva', '0005_remove_userprofile_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10),
        ),
    ]
