# Generated by Django 6.0.3 on 2026-03-06 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arva', '0005_project_etd_project_is_project_project_pm_assignee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
