# Generated by Django 6.0.3 on 2026-03-06 07:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arva', '0006_project_is_closed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AISettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('google', 'Google Gemini'), ('openai', 'OpenAI')], default='google', max_length=20)),
                ('api_key', models.CharField(help_text='API Key untuk AI provider', max_length=500)),
                ('model_name', models.CharField(default='gemini-2.5-flash', help_text='Model AI yang akan digunakan', max_length=50)),
                ('temperature', models.DecimalField(decimal_places=2, default=0.7, help_text='Kreativitas AI (0.0 = deterministik, 1.0 = sangat kreatif)', max_digits=3)),
                ('max_tokens', models.IntegerField(default=2048, help_text='Maximum tokens untuk response')),
                ('ai_priority_enabled', models.BooleanField(default=True, help_text='Enable/Disable fitur AI Priority Queue')),
                ('ai_chat_enabled', models.BooleanField(default=True, help_text='Enable/Disable fitur AI Chat Assistant')),
                ('priority_analysis_prompt', models.TextField(blank=True, help_text='Custom prompt untuk analisis prioritas (kosongkan untuk menggunakan default)')),
                ('chat_system_prompt', models.TextField(blank=True, help_text='Custom system prompt untuk chat (kosongkan untuk menggunakan default)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_ai_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Settings',
                'verbose_name_plural': 'AI Settings',
            },
        ),
    ]
