# Generated by Django 6.0.3 on 2026-03-10 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arva', '0007_aisettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='aisettings',
            name='base_url',
            field=models.CharField(blank=True, default='http://localhost:8080/v1', help_text='Base URL untuk AI provider (khusus Open Claw)', max_length=500),
        ),
        migrations.AddField(
            model_name='aisettings',
            name='custom_model_name',
            field=models.CharField(blank=True, help_text="Nama model custom jika memilih 'Custom Model' di Open Claw", max_length=100),
        ),
        migrations.AlterField(
            model_name='aisettings',
            name='api_key',
            field=models.CharField(blank=True, help_text='API Key untuk AI provider (kosongkan jika tidak perlu)', max_length=500),
        ),
        migrations.AlterField(
            model_name='aisettings',
            name='model_name',
            field=models.CharField(default='llama-3.2-3b', help_text='Model AI yang akan digunakan', max_length=100),
        ),
        migrations.AlterField(
            model_name='aisettings',
            name='provider',
            field=models.CharField(choices=[('google', 'Google Gemini'), ('openclaw', 'Open Claw (Self-hosted)'), ('openai', 'OpenAI')], default='openclaw', max_length=20),
        ),
    ]
