# Generated by Django 6.0.3 on 2026-03-26 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arva', '0008_aisettings_base_url_aisettings_custom_model_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aisettings',
            name='ollama_url',
            field=models.CharField(blank=True, default='http://localhost:11434/v1', help_text='Ollama endpoint (auto-switch)', max_length=500),
        ),
        migrations.AddField(
            model_name='aisettings',
            name='openclaw_url',
            field=models.CharField(blank=True, default='http://localhost:8080/v1', help_text='Open Claw endpoint (auto-switch)', max_length=500),
        ),
        migrations.AlterField(
            model_name='aisettings',
            name='base_url',
            field=models.CharField(blank=True, default='http://localhost:11434/v1', help_text='Base URL untuk AI provider (Ollama: http://localhost:11434/v1, Open Claw: http://localhost:8080/v1)', max_length=500),
        ),
    ]
