# Generated by Django 6.0.3 on 2026-03-26 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arva', '0009_add_ollama_endpoints'),
    ]

    operations = [
        migrations.AddField(
            model_name='aisettings',
            name='assistant_model',
            field=models.CharField(default='qwen2.5:7b', help_text='Model untuk AI Chat Assistant dan Priority Analysis', max_length=100),
        ),
        migrations.AddField(
            model_name='aisettings',
            name='custom_assistant_model',
            field=models.CharField(blank=True, help_text='Custom model untuk AI Assistant', max_length=100),
        ),
        migrations.AddField(
            model_name='aisettings',
            name='custom_developer_model',
            field=models.CharField(blank=True, help_text='Custom model untuk AI Developer', max_length=100),
        ),
        migrations.AddField(
            model_name='aisettings',
            name='developer_model',
            field=models.CharField(default='codellama:13b', help_text='Model untuk pengembangan fitur dan perbaikan bug', max_length=100),
        ),
        migrations.AlterField(
            model_name='aisettings',
            name='model_name',
            field=models.CharField(default='llama3.2:3b', help_text='Model AI default (fallback)', max_length=100),
        ),
    ]
