# Generated by Django 6.0.3 on 2026-03-26 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arva', '0010_separate_ai_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIFeatureRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('request_type', models.CharField(choices=[('bugfix', 'Bug Fix'), ('feature', 'Feature Baru'), ('improvement', 'Improvement'), ('refactor', 'Refactor')], default='feature', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('analyzing', 'Analyzing'), ('planning', 'Planning'), ('generating', 'Generating'), ('reviewing', 'Reviewing'), ('applying', 'Applying'), ('testing', 'Testing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('related_files', models.JSONField(blank=True, default=list, help_text='List file yang terkait')),
                ('affected_models', models.JSONField(blank=True, default=list, help_text='Model Django yang terpengaruh')),
                ('analysis_result', models.JSONField(blank=True, default=dict, help_text='Hasil analisis AI')),
                ('implementation_plan', models.JSONField(blank=True, default=dict, help_text='Rencana implementasi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_ai_requests', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Feature Request',
                'verbose_name_plural': 'AI Feature Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AICodeChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=500)),
                ('change_type', models.CharField(choices=[('add', 'Add'), ('modify', 'Modify'), ('delete', 'Delete')], default='modify', max_length=10)),
                ('original_code', models.TextField(blank=True, help_text='Kode sebelum perubahan')),
                ('new_code', models.TextField(help_text='Kode setelah perubahan')),
                ('diff_content', models.TextField(help_text='Unified diff format')),
                ('line_start', models.IntegerField(blank=True, help_text='Baris awal perubahan', null=True)),
                ('line_end', models.IntegerField(blank=True, help_text='Baris akhir perubahan', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('applied', 'Applied'), ('rolled_back', 'Rolled Back')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_comment', models.TextField(blank=True)),
                ('backup_path', models.CharField(blank=True, help_text='Path ke backup file', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_changes', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_changes', to='arva.aifeaturerequest')),
            ],
            options={
                'verbose_name': 'AI Code Change',
                'verbose_name_plural': 'AI Code Changes',
                'ordering': ['created_at'],
            },
        ),
    ]
