# Generated by Django 6.0.3 on 2026-03-27 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arva', '0011_aifeaturerequest_aicodechange'),
    ]

    operations = [
        migrations.AddField(
            model_name='aicodechange',
            name='error_message',
            field=models.TextField(blank=True, help_text='Error message if generation failed'),
        ),
        migrations.AddField(
            model_name='aicodechange',
            name='has_error',
            field=models.BooleanField(default=False, help_text='True if code generation failed for this change'),
        ),
    ]
