# Generated by Django 4.2.25 on 2026-03-30 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arva', '0012_aicodechange_error_message_aicodechange_has_error'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aisettings',
            name='provider',
            field=models.CharField(choices=[('google', 'Google Gemini'), ('openclaw', 'Open Claw (Self-hosted)'), ('openai', 'OpenAI'), ('qoder', 'Qoder (Claude)')], default='openclaw', max_length=20),
        ),
    ]
