# Generated by Django 6.0.3 on 2026-04-02 06:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arva', '0013_alter_aisettings_provider'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aifeaturerequest',
            name='cancel_reason',
            field=models.TextField(blank=True, help_text='Alasan pembatalan'),
        ),
        migrations.AddField(
            model_name='aifeaturerequest',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, help_text='Waktu pembatalan', null=True),
        ),
        migrations.AddField(
            model_name='aifeaturerequest',
            name='complexity_score',
            field=models.IntegerField(blank=True, help_text='Skor kompleksitas (1-100)', null=True),
        ),
        migrations.AddField(
            model_name='aifeaturerequest',
            name='current_step',
            field=models.IntegerField(default=0, help_text='Langkah saat ini dalam proses'),
        ),
        migrations.AddField(
            model_name='aifeaturerequest',
            name='dependency_graph',
            field=models.JSONField(blank=True, default=dict, help_text='Graf dependensi antar file'),
        ),
        migrations.AddField(
            model_name='aifeaturerequest',
            name='error_count',
            field=models.IntegerField(default=0, help_text='Jumlah error yang terjadi'),
        ),
        migrations.AddField(
            model_name='aifeaturerequest',
            name='estimated_effort',
            field=models.CharField(blank=True, help_text='Estimasi waktu pengerjaan', max_length=50),
        ),
        migrations.AddField(
            model_name='aifeaturerequest',
            name='is_cancelled',
            field=models.BooleanField(default=False, help_text='Apakah request dibatalkan'),
        ),
        migrations.AddField(
            model_name='aifeaturerequest',
            name='last_error',
            field=models.TextField(blank=True, help_text='Error terakhir yang terjadi'),
        ),
        migrations.AddField(
            model_name='aifeaturerequest',
            name='progress_percent',
            field=models.IntegerField(default=0, help_text='Persentase progress (0-100)'),
        ),
        migrations.AddField(
            model_name='aifeaturerequest',
            name='step_description',
            field=models.CharField(blank=True, help_text='Deskripsi langkah saat ini', max_length=255),
        ),
        migrations.AddField(
            model_name='aifeaturerequest',
            name='total_steps',
            field=models.IntegerField(default=7, help_text='Total langkah dalam proses'),
        ),
        migrations.AlterField(
            model_name='aifeaturerequest',
            name='analysis_result',
            field=models.JSONField(blank=True, default=dict, help_text='Hasil analisis AI terhadap codebase'),
        ),
        migrations.AlterField(
            model_name='aifeaturerequest',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_ai_requests', to=settings.AUTH_USER_MODEL, verbose_name='Ditugaskan Kepada'),
        ),
        migrations.AlterField(
            model_name='aifeaturerequest',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Waktu Selesai'),
        ),
        migrations.AlterField(
            model_name='aifeaturerequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Waktu Dibuat'),
        ),
        migrations.AlterField(
            model_name='aifeaturerequest',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_requests', to=settings.AUTH_USER_MODEL, verbose_name='Dibuat Oleh'),
        ),
        migrations.AlterField(
            model_name='aifeaturerequest',
            name='description',
            field=models.TextField(verbose_name='Deskripsi'),
        ),
        migrations.AlterField(
            model_name='aifeaturerequest',
            name='implementation_plan',
            field=models.JSONField(blank=True, default=dict, help_text='Rencana implementasi yang dibuat AI'),
        ),
        migrations.AlterField(
            model_name='aifeaturerequest',
            name='priority',
            field=models.CharField(choices=[('low', 'Rendah'), ('medium', 'Sedang'), ('high', 'Tinggi'), ('critical', 'Kritis')], default='medium', max_length=20, verbose_name='Prioritas'),
        ),
        migrations.AlterField(
            model_name='aifeaturerequest',
            name='related_files',
            field=models.JSONField(blank=True, default=list, help_text='Daftar file yang terkait dengan request ini'),
        ),
        migrations.AlterField(
            model_name='aifeaturerequest',
            name='request_type',
            field=models.CharField(choices=[('bugfix', 'Perbaikan Bug'), ('feature', 'Fitur Baru'), ('improvement', 'Peningkatan'), ('refactor', 'Refactor')], default='feature', max_length=20, verbose_name='Tipe Request'),
        ),
        migrations.AlterField(
            model_name='aifeaturerequest',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Waktu Dimulai'),
        ),
        migrations.AlterField(
            model_name='aifeaturerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Menunggu'), ('validating', 'Memvalidasi Request'), ('discovering', 'Menemukan File Terkait'), ('analyzing', 'Menganalisis Kode'), ('planning', 'Membuat Rencana'), ('generating', 'Menghasilkan Kode'), ('validating_code', 'Memvalidasi Kode'), ('reviewing', 'Menunggu Review'), ('applying', 'Menerapkan Perubahan'), ('testing', 'Menguji'), ('completed', 'Selesai'), ('failed', 'Gagal'), ('cancelled', 'Dibatalkan')], default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='aifeaturerequest',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Judul'),
        ),
        migrations.AlterField(
            model_name='aifeaturerequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Waktu Diupdate'),
        ),
    ]
