# Generated by Django 6.0.3 on 2026-04-18 15:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arva', '0014_aifeaturerequest_cancel_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='aisettings',
            name='developer_model',
            field=models.CharField(default='deepseek-coder:6.7b', help_text='Model untuk pengembangan fitur dan perbaikan bug', max_length=100),
        ),
        migrations.AlterField(
            model_name='aisettings',
            name='provider',
            field=models.CharField(choices=[('google', 'Google Gemini'), ('openclaw', 'Open Claw (Self-hosted)'), ('openai', 'OpenAI'), ('qoder', 'Qoder (Claude)'), ('deepseek', 'DeepSeek API ⭐ Recommended')], default='openclaw', max_length=20),
        ),
        migrations.CreateModel(
            name='AIPriorityUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('last_used_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_priority_usage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Priority Usage',
                'verbose_name_plural': 'AI Priority Usage',
                'unique_together': {('user', 'date')},
            },
        ),
    ]
