# Generated by Django 6.0.3 on 2026-04-19 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arva', '0015_alter_aisettings_developer_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aisettings',
            name='ai_developer_enabled',
            field=models.BooleanField(default=True, help_text='Enable/Disable fitur AI Developer'),
        ),
    ]
